[package]
name = "cdk-ffi-go"
edition = "2021"
rust-version = "1.85.0"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/cashubtc/cdk"
repository = "https://github.com/cashubtc/cdk.git"
version = "0.18.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]
name = "cdk_ffi_go"

[dependencies]
cdk-ffi = { git = "https://github.com/crodas/cdk", rev = "9f188e135c84034c7c7b9151884fa4066cdfcd53", features = ["npubcash", "nwc", "bip353"] }

[lints]


[workspace]

[profile.release]
lto = true
strip = true
codegen-units = 1
